project:
  type: website

website:
  site-url: https://example.com
  title: "multilingual_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




babelquarto:
  languagelinks: navbar
  languagecodes:
  - name: en
    text: "Version in en"
  - name: ja
    text: "Version in ja"
  mainlanguage: 'ja'
  languages: ['en']
title-en: title in en
description-en: description in en
author-en: author in en
lang: ja
