project:
  type: website
  output-dir: docs

website:
  title: "多言語サイト"
  site-url: https://joelnitta.github.io/multilingual_website/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




babelquarto:
  languagecodes:
  - name: en
    text: "English"
  - name: ja
    text: "日本語"
  mainlanguage: 'ja'
  languages: ['en']
title-en: Multilingual Website
description-en: Demo of a multilingual website
author-en: Joel Nitta
lang: ja
